//! # envy
//!
//! A utility to generate an entire analysis environment for data science stacks
//!
//!
//! ## Examples
//! ```bash
//! # Initialise analysis environment
//! envy init
//!
//! # Generate templated python analysis file
//! envy template py --output_name "test.py"
//!
//! ```
use std::{
    env, fs,
    path::{Path, PathBuf},
    process::Command,
};

use anyhow::Result;
use clap::{Parser, Subcommand};
use rust_embed::RustEmbed;

#[derive(Parser, Debug)]
#[command(
    author,
    version,
    name = "envy",
    about = "Instantly setup production ready data science environments",
    help_template = "{bin} {version}\n\n{about-with-newline}\n{usage-heading}\n{usage}\n\n{all-args}"
)]
#[command(propagate_version = true)]
struct Args {
    /// Turn debugging information on
    #[arg(short, long, global = true)]
    debug: bool,

    #[command(subcommand)]
    command: Commands,
}

/// Sub-command enum
#[derive(Subcommand, Debug)]
enum Commands {
    /// Initialise analysis environment
    Init,
    Template {
        #[arg(value_parser = ["eda", "py", "api", "r"])]
        template: String,

        /// Optional output filename. If omitted, a default name is used.
        #[arg(short, long)]
        output_name: Option<String>,
    },
    Sync,
}

/// Main entry point for binary
fn main() -> Result<()> {
    let args = Args::parse();

    match args.command {
        Commands::Init => setup_environment(),
        Commands::Template {
            template,
            output_name,
        } => generate_template(&template, &output_name),
        Commands::Sync => sync_environment(),
    }
}

#[derive(RustEmbed)]
#[folder = "templates/"]
struct Asset;

/// This list of empty template dirs is generated by build.rs so that we don't have to hard-code empty dirs
/// in the source code, given that rust-embed does not embed empty directories.
const DIRS_JSON: &str = include_str!(concat!(env!("OUT_DIR"), "/template_dirs.json"));

/// Setup Analysis Environment
pub fn setup_environment() -> Result<()> {
    let current_dir = env::current_dir()?;
    let project_name = current_dir
        .file_name()
        .and_then(|os_str| os_str.to_str())
        .unwrap_or("data_project");

    println!("🚀 Scaffolding data analysis environment...");

    let empty_dirs: Vec<String> = serde_json::from_str(DIRS_JSON)
        .map_err(|e| std::io::Error::new(std::io::ErrorKind::InvalidData, e))?;

    for dir in empty_dirs {
        fs::create_dir_all(&dir)?;
        println!("  📁 Created directory: {}", dir);
    }

    println!("\n📦 Instantiating configuration files...");

    for file_path in Asset::iter() {
        let path_str = file_path.as_ref();
        let file = Asset::get(path_str).unwrap();
        let relative_path = PathBuf::from(path_str);

        let (target_path, final_content) = match path_str {
            "template.Rproj" => {
                let dynamic_filename = format!("{}.Rproj", project_name);
                let content_str = String::from_utf8_lossy(&file.data);
                let replaced = content_str.replace("{{PROJECT_NAME}}", project_name);
                (PathBuf::from(dynamic_filename), replaced.into_bytes())
            }
            "pixi.toml" => {
                let content_str = String::from_utf8_lossy(&file.data);
                let replaced = content_str.replace("{{PROJECT_NAME}}", project_name);
                (relative_path, replaced.into_bytes())
            }
            _ => (relative_path, file.data.to_vec()),
        };

        if !target_path.exists() {
            fs::write(&target_path, final_content)?;
            println!("  📄 Created configuration: {}", target_path.display());
        }
    }

    Ok(())
}

// Embed boilerplate files into the binary
#[derive(RustEmbed)]
#[folder = "boilerplates/"]
struct Boilerplate;

pub fn generate_template(template: &str, output_name: &Option<String>) -> Result<()> {
    let (embedded_file, default_output) = match template {
        "eda" => ("eda.ipynb", "eda.ipynb"),
        "py" => ("script.py", "main.py"),
        "api" => ("api.py", "api.py"),
        "r" => ("script.r", "script.r"),
        _ => unreachable!(), // Clap's value_parser guarantees we only get valid strings
    };

    // If they provided a name, use it. Otherwise, fall back to the default.
    let final_output = output_name.as_deref().unwrap_or(default_output);
    let target_path = PathBuf::from(final_output);

    if let Some(file) = Boilerplate::get(embedded_file) {
        if !target_path.exists() {
            fs::write(&target_path, file.data)?;
            println!(
                "  📄 Generated template '{}' at {}",
                template,
                target_path.display()
            );
        } else {
            println!("⚠️  {} already exists, skipping.", target_path.display());
        }
    } else {
        eprintln!("❌ Template file '{}' missing from binary!", embedded_file);
    }

    Ok(())
}

pub fn sync_environment() -> Result<()> {
    println!("🔄 Detecting environment configuration...");

    let has_pixi = Path::new("pixi.toml").try_exists()?;
    let has_pyproject = Path::new("pyproject.toml").try_exists()?;

    // Route to the correct tool using a tuple match
    let (tool, args): (&str, &[&str]) = match (has_pixi, has_pyproject) {
        // If pixi.toml exists, or both exist, pixi takes priority
        (true, _) => ("pixi", &["install"]),

        // If ONLY pyproject.toml exists, use the Python ecosystem tool
        (false, true) => ("uv", &["sync"]),

        (false, false) => {
            eprintln!("❌ Neither pixi.toml nor pyproject.toml found in this directory.");
            return Ok(());
        }
    };

    println!(
        "🛠️  Syncing environment using `{} {}`...",
        tool,
        args.join(" ")
    );

    let status = Command::new(tool).args(args).status()?;

    if status.success() {
        println!("✅ Environment synced successfully via {}.", tool);
    } else {
        eprintln!("❌ Failed to sync environment via {}.", tool);
    }

    Ok(())
}

// After consideration deletion should not be automated.
// fn clean() -> Result<()> {
//     unimplemented!("TODO");
// }
