[build]
target = "x86_64-unknown-linux-musl"

# Statically link the C runtime for MUSL targets. At the time of writing (2026-06-01), this is
# the default. But the plan is for the default to change to dynamic linking.
# The whole point of MUSL with respect to ripgrep is to create a fully
# statically linked executable.
#
# See: https://github.com/rust-lang/compiler-team/issues/422
# See: https://github.com/rust-lang/compiler-team/issues/422#issuecomment-812135847
[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-Z", "threads=8",
  "-C", "target-feature=+crt-static",
  "-C", "link-self-contained=yes",
]
